Samples:
  - Name: "Detector Variation"
    #FilePath: path: "/exp/dune/data/users/cdalmazz/gitTools/atmospherics-tools/detsys/data/Detsim_lifetime12480_2/"
    FilePath: "/exp/dune/data/users/cdalmazz/gitTools/atmospherics-tools/detsys/data/subsetDetsim/"
    SubDirectoryName: "cafmaker"
    Colour: 1
    LineStyle: 1
  - Name: "Wiremod"
    #FilePath: "/exp/dune/data/users/cdalmazz/gitTools/atmospherics-tools/detsys/data/Wiremod_lifetime12480_2/"
    FilePath: "/exp/dune/data/users/cdalmazz/gitTools/atmospherics-tools/detsys/data/subsetWiremod/"
    SubDirectoryName: "cafmaker"
    Colour: 2
    LineStyle: 2

#output:
#  file: "comparison.root"

#quantities:

#  - name: "erec"
#    bins: 200
#    min: -5
#    max: 5

#  - name: "RecoCZ"
#    bins: 200
#    min: -1
#    max: 1

#  - name: "had_erec"
#    bins: 200
#    min: -5
#    max: 5


AnalysisBinning:
  - Selection: "NuMu" #Selection Name
    kSelection: 1 #Index which matches one of the selection enums defined here: https://github.com/DUNE/atmospherics-tools/blob/b25e0400f2a571a4e4b6e4bddee58579e7dc37b0/detsys/src/Constants.h#L5-L10
    #kNuRecoCosZ: [-1.001, -0.6, -0.2, 0.2, 0.6, 1.001]
    kNuRecoCosZ: [-1.001, 1.001]
    kNuERec: [0, 1.28, 1e8]
  - Selection: "NuE"
    kSelection: 0
    kNuRecoCosZ: [-1.001, 1.001]
    kNuERec: [0, 1.28, 1e8]
    
Observables:
  - Name: "Reco Neutrino Energy"
    Axes:
      - Variable: "kNuERec"
        IsLog: true
        Label: "Reco Neutrino Energy [GeV]"
        Binning: [0.05,0.2,0.4,0.6,0.8,1.2,1.6,2.0,4.0,10.]

  - Name: "Reco Hadron Energy"
    Axes:
      - Variable: "kHadERec"
        IsLog: true
        Label: "Reco Hadron Energy [GeV]"
        Binning: [0.05,0.2,0.4,0.6,0.8,1.2,1.6,2.0,4.0,10.]

  - Name: "Reco Lepton Energy"
    Axes:
      - Variable: "kLepERec"
        IsLog: true
        Label: "Reco Lepton Energy [GeV]"
        Binning: [0.05,0.2,0.4,0.6,0.8,1.2,1.6,2.0,4.0,10.]


Fluxes:
  FluxDir: "/cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/TaskForce_Flux/atmos/Honda_interp/"
  nue: "honda_2d_homestake_2015_nue.root"
  nuebar: "honda_2d_homestake_2015_nuebar.root"
  numu: "honda_2d_homestake_2015_numu.root"
  numubar: "honda_2d_homestake_2015_numubar.root"
  refflux: "/cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/TaskForce_Flux/atmos/Honda_interp/honda_2d_homestake_2015_numu.root"


NuOscillator:

  General:
    Verbosity: "NONE"
    CosineZIgnored: false
    CalculationType: "Binned"

  Binned:
    FileName: "./Inputs/ExampleAtmosphericBinning.root"
    EnergyAxisHistName: "EnergyAxisBinning"
    CosineZAxisHistName: "CosineZAxisBinning"

  OscProbCalcerSetup:
    ImplementationName: "CUDAProb3"
    EarthModelFileName: "./build/_deps/cudaprob3-src/models/PREM_4layer.dat"
    UseEarthModelSystematics: false
    Layers: 4
    UseProductionHeightsAveraging: false
    ProductionHeightsFileName: "./inputs/ProdHeightDist_E561_cZ520_N1_hbin2.5.root"
    ProductionHeightsHistFlavourSuffixes:
      Nue: "nue"
      Numu: "numu"
      Nutau: "numu"
      Nuebar: "nuebar"
      Numubar: "numubar"
      Nutaubar: "numubar"
    OscChannelMapping:
      - Entry: "Electron:Electron"
      - Entry: "Electron:Muon"
      - Entry: "Electron:Tau"
      - Entry: "Muon:Electron"
      - Entry: "Muon:Muon"
      - Entry: "Muon:Tau"
      - Entry: "Tau:Electron"
      - Entry: "Tau:Muon"
      - Entry: "Tau:Tau"

  OscillationParameters:
    sin2_th12: 3.07e-1
    sin2_th23: 5.28e-1
    sin2_th13: 2.18e-2
    dm2_12: 7.53e-5
    dm2_23: 2.509e-3
    delta_cp: -1.601
    prod_h: 25
